### ISSUE TITLE
Version tags won't work with go modules. 

### ISSUE THREAD

**Issue by snowzach** [florianl/go-nflog#11]
You have a 2.0.0 and 3.0.0 tags but you haven't set it up correctly to work with go modules. Could you change the tags to 1.2.0 and 1.3.0 respectively? The major tag changes should be when you make incompatible changes.

**Comment by florianl** [comment]
There was actually a hard change that breaks backward compatibility:

https://github.com/florianl/go-nflog/blob/v2.0.0/nflog.go#L99
```
type HookFunc func(m Msg) int
```

https://github.com/florianl/go-nflog/blob/v3.0.0/nflog.go#L126
```
type HookFunc func(a Attribute) int
```

**Comment by snowzach** [comment]
Sure.. no problem.. I think you need to change your `go.mod` file so the first line reads:
`github.comflorianl/go-nflog/v3` and when we import it we need to import it as `github.comflorianl/go-nflog/v3` 

Otherwise, when I just import `github.comflorianl/go-nflog` it will default to the tag `v1.1.0`

**Comment by florianl** [comment]
Not sure if this works out. A `v3` suffix in `go.mod`  expects a `v3` folder in the repo with the code. That's how I'm reading https://blog.golang.org/v2-go-modules

**Comment by snowzach** [comment]
This is the main project I know that uses major module versions. I don't believe they use that subfolder. https://github.com/olivere/elastic

I think the v2 folder would be used if you want to fool old code that doesn't use modules into not using the v2 version. Since you already have v3 on master any old code that uses this repo would be broken anyhow as it's pulling in the new function names.

**Comment by florianl** [comment]
Thanks for the hint. I will have a look at it.
As an alternative you can also specify version in the `get` command:
```
$ go get github.com/florianl/go-nflog@master
$ go get github.com/florianl/go-nflog@a08ed2706aa75a046fa66f427b1205d0a42a09f5
```
While `master` will always point to the latest commit the second points to the currently most recent commit.
