### ISSUE TITLE
registered function will not be called

### ISSUE THREAD

**Issue by peanut-cc** [florianl/go-nflog#19]
When multiple iptables rules are set, the registered function will not be called after running for a period of time

**Comment by florianl** [comment]
Hi @peanut-cc,
And thanks for the report!
Can you share some more details or provide a minimal example that reproduces the issue? How does the iptables rules look like and how many use the same nflog group? What is the output of the logger, that you can attach to the config https://pkg.go.dev/github.com/florianl/go-nflog/v2#Config?
Which version of this package are you using?

**Comment by peanut-cc** [comment]
Thank you very much. There will be problems when I use the Register method. It seems that I have solved the problem by using RegisterWithErrorFunc. Is it the problem of V1 version?
Here is the test code：
```
package main

import (
	"context"
	"fmt"
	"github.com/coreos/go-iptables/iptables"
	"github.com/florianl/go-nflog/v2"
)

const (
	table       = "filter"
	chain       = "nflog"
	nflog_group = "100"
)

func initIptable() error {
	ipt, err := iptables.NewWithProtocol(iptables.ProtocolIPv4)
	if err != nil {
		return err
	}
	ipt.ClearChain(table, chain)
	ipt.Delete(table, "INPUT", "-j", chain)
	err = ipt.Insert(table, "INPUT", 1, "-j", chain)
	portRange := fmt.Sprintf("%v:%v", 20, 65535)

	rulespec := ruleSpec("tcp", portRange)
	if err = ipt.AppendUnique(table, chain, rulespec...); err != nil {
		return err
	}
	syncRule := synRuleSpec("tcp", portRange)
	if err = ipt.AppendUnique(table, chain, syncRule...); err != nil {
		return err
	}
	return nil
}

// ruleSpec
func ruleSpec(proto, dportStr string) (rulespec []string) {
	rulespec = []string{
		"-p", proto,
		"-m", proto,
		"-m", "multiport",
		"--dports", dportStr,
		"--tcp-flags", "FIN,SYN,RST,PSH,ACK,URG", "FIN,PSH,URG",
		"-j", "NFLOG",
		"--nflog-group", nflog_group,
	}
	return rulespec
}

// syn rulespec
func synRuleSpec(proto, dportStr string) (rulespec []string) {
	rulespec = []string{
		"-p", proto,
		"-m", proto,
		"-m", "multiport",
		"--dports", dportStr,
		"--tcp-flags", "FIN,SYN,RST,PSH,ACK,URG", "SYN",
		"-j", "NFLOG",
		"--nflog-group", nflog_group,
	}
	return rulespec
}

func callback(attrs nflog.Attribute) int {
	fmt.Println("start to callback")
	return 0
}

func errFunc(e error) int {
	fmt.Printf("error is %v", e)
	return 0
}

func main() {
	err := initIptable()
	if err != nil {
		fmt.Printf("init iptable error:%v", err)
		return
	}
	config := nflog.Config{
		Group:    100,
		Copymode: nflog.CopyPacket,
	}
	nf, err := nflog.Open(&config)
	if err != nil {
		fmt.Println("could not open nflog socket:", err)
		return
	}
	defer nf.Close()
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	// err = nf.RegisterWithErrorFunc(ctx, callback, errFunc)
	err = nf.Register(ctx, callback)
	if err != nil {
		fmt.Printf("register callback error:%v", err)
		return
	}
	<-ctx.Done()
}

```
Run the program on Linux and start nmap scanning on another machine
For example, the program executes nmap on 192.168.1.100, Execute nmap - SS 192.168.1.100 - P 10-10000 at 192.168.1.200

**Comment by florianl** [comment]
> There will be problems when I use the Register method. It seems that I have solved the problem by using RegisterWithErrorFunc. Is it the problem of V1 version?

The error handling function in previous versions dropped the hook without further notice. This issue got solved with v2.

**Comment by peanut-cc** [comment]
> > There will be problems when I use the Register method. It seems that I have solved the problem by using RegisterWithErrorFunc. Is it the problem of V1 version?
> 
> The error handling function in previous versions dropped the hook without further notice. This issue got solved with v2.

Thank you very much！
