### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by shotahino** [florianl/go-nflog#3]
I did something almost identical to your example.
I have an iptable rule with `-j NFLOG --nflog-group 100` and my registered callback does not seem to run.

However, I can see the packets hitting the rule if I do `tcpdump -i nflog:100`. 
How would you go about debugging this? 

My platform is linux kernel 3.14.

**Comment by shotahino** [comment]
One thing to note: Although tcpdump seems to work, I do get a warning like this:
```
tcpdump: WARNING: SIOCGIFADDR: nflog:100: No such device
```
Not sure if this is concerning.

**Comment by florianl** [comment]
If possible, can you provide a code for reproducing the error. A complete runnable program is good. A link on play.golang.org is best.

You can check with `# cat /proc/net/netfilter/nfnetlink_log` if there is a listener for a specific nflog group. But there can always only be one listern - so either tcpdump or a other listner, like your programm using go-nflog.

Did you use the `Logger` in [Config](https://godoc.org/github.com/florianl/go-nflog#Config) to get more insights?

**Comment by shotahino** [comment]
> You can check with # cat /proc/net/netfilter/nfnetlink_log
Yep, this looks correct. The PID of my program is listed with the group id (100), although I don't know how to parse the line.
```
root@xxxx:~# cat /proc/net/netfilter/nfnetlink_log 
  100   4988     0 2 65531    100  1
```

> so either tcpdump or a other listner, like your programm using go-nflog.

Yep, that sounds right. When my program is running, I cannot run `tcpdump`.

> Did you use the Logger in Config to get more insights?

I just tried, and getting a spew of logs
```
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
Apr 23 15:19:08 xxxx user.info /usr/bin/test[3960]: 2019/04/23 Could not receive message: netlink receive: recvmsg: i/o timeout
```
^^^ Is this expected?

**Comment by shotahino** [comment]
My program is almost identical to yours,

```golang
import (
	"context"
	"log/syslog"

	nflog "github.com/florianl/go-nflog"
)

func Run() {
	sysLogger, err := syslog.NewLogger(syslog.LOG_INFO|syslog.LOG_USER, 1)
	if err != nil {
		return
	}

	config := nflog.Config{
		Group:    100,
		Copymode: nflog.NfUlnlCopyPacket,
		Logger:   sysLogger,
	}

	nf, err := nflog.Open(&config)
	if err != nil {
		return
	}
	defer nf.Close()

       // I changed here so that context never expires.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	fn := func(m nflog.Msg) int {
               // I added my own logging here.
               // My logging does not show up to syslog.
	       return 0
	}

	// Register your function to listen on nflog group 100
	log.Log().Infof("Registering callback for access violation")
	err = nf.Register(ctx, fn)
	if err != nil {
		return
	}

	// Block till the context expires
	<-ctx.Done()
}
```

The only part I changed is that I do not expire the context so that this keeps running forever.
The logging I added in the callback does not show up to syslog, hence I feel it is not getting triggered.

**Comment by florianl** [comment]
Did you test your code with the recent changes and setting`ReadTimeout`?

**Comment by shotahino** [comment]
@florianl Yes, it works with not applying read timeout.

I actually have another question. For me, it does not compile unless I upgrade my environment to go 1.12, and it is because of these https://github.com/mdlayher/netlink/blob/master/conn_linux.go#L536-L546, which your library imports. Could you confirm?

**Comment by florianl** [comment]
yes - go 1.12 is required to use these timeouts.
