### ISSUE TITLE
Panic when readTimeout is not set

### ISSUE THREAD

**Issue by shotahino** [florianl/go-nflog#5]
The bug was introduced in https://github.com/florianl/go-nflog/pull/4

We should check if this function is non-nil here.
https://github.com/florianl/go-nflog/blob/master/nflog.go#L190
```go
    if nflog.setReadTimeout != nil {
        nflog.setReadTimeout()
    }
```

Otherwise, this will panic.

**Comment by florianl** [comment]
Thanks for reporting this. I handled this case in http://github.com/florianl/go-nfqueue, but misses to port it here.
So https://github.com/florianl/go-nflog/commit/8329a9a5168b97d6098a1a9f67582f440f1ef855 fixes this now. Can you confirm, that it is now working as expected?

**Comment by shotahino** [comment]
@florianl Thank you. The fix works.
